dummy_response =[
                {
                    "date":"2024-01-01",
                    "name":"stock1",
                    "value":232
                },
                 {
                    "date":"2024-01-01",
                    "name":"stock1",
                    "value":232
                },
                 {
                    "date":"2024-01-01",
                    "name":"stock1",
                    "value":232
                },
                 {
                    "date":"2024-01-01",
                    "name":"stock1",
                    "value":232
                },
                 {
                    "date":"2024-01-01",
                    "name":"stock1",
                    "value":232
                },
                 {
                    "date":"2024-01-01",
                    "name":"stock1",
                    "value":232
                },
]